### ISSUE TITLE
"No module named.."

### ISSUE THREAD

**Issue by yusijs** [skrutt/broadlink_sp4_customcomponent#3]
Added the sp4 directory to custom_components, restarted home assistant and wound up with this error:

`Platform error switch.clas - No module named 'custom_components.sp4.const'`

My config
```

switch:
  - platform: clas
    host: 192.168.86.216
    mac: "24:df:a7:2d:81:ce"
    type: sp4

```

Any suggestions on what I've messed up?
